// <auto-generated />
namespace MVC_Complete_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CategoryEntitySubCategoryMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CategoryEntitySubCategoryMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202011210446397_CategoryEntitySubCategoryMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
